// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using a.Models;

#nullable disable

namespace a.Migrations
{
    [DbContext(typeof(CamDataContext))]
    partial class CamDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("a.Models.Cam", b =>
                {
                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("CamName")
                        .HasColumnType("TEXT");

                    b.HasKey("IpAddress");

                    b.ToTable("Cams");
                });

            modelBuilder.Entity("a.Models.Temp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CamIpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxTemp")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinTemp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeReading")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CamIpAddress");

                    b.ToTable("Temps");
                });

            modelBuilder.Entity("a.Models.Temp", b =>
                {
                    b.HasOne("a.Models.Cam", null)
                        .WithMany("Temps")
                        .HasForeignKey("CamIpAddress");
                });

            modelBuilder.Entity("a.Models.Cam", b =>
                {
                    b.Navigation("Temps");
                });
#pragma warning restore 612, 618
        }
    }
}
